# Generated by Django 2.1.1 on 2019-07-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim_app', '0002_auto_20190508_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
    ]
