# Generated by Django 2.1.1 on 2019-07-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim_app', '0003_remove_category_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='_category_categories_+', to='pim_app.Category'),
        ),
    ]
